project_id = "tcciipxgeomysyvwyzyi"

[functions.places-search]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.activities-search]
verify_jwt = false

[functions.profile]
verify_jwt = false

[functions.geocode]
verify_jwt = false
