project_id = "tcciipxgeomysyvwyzyi"

[functions.interpret-voice]
verify_jwt = false

[functions.places-search]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.proxy-photo]
verify_jwt = false

[functions.activities-search]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.parse-onboarding-answer]
verify_jwt = true

[functions.weather]
verify_jwt = false

[functions.interpret-schedule-voice]
verify_jwt = false

[functions.check-availability]
verify_jwt = true

[functions.generate-notifications]
verify_jwt = true

[functions.fetch-weather-forecast]
verify_jwt = false
